### ISSUE TITLE
Incorrect conversion from JPG CMYK => RGB (using Image Magick convert works)

### ISSUE THREAD

**Issue by jxtps** [rmagick-temp/rmagick#4] opened 2010-04-23 14:43 UTC
When converting a JPG that is in the CMYK colorspace to the RGB colorspace using RMagick, the operation produces an image that looks like it has inverted colors (black turns to white). Using the Image Magick convert tool does not exhibit this problem. Sample image for which this happens together with the outputs are unfortunately not attached since github doesn't seem to support attachments for bugs. Email me for the files. 

Version information and steps to reproduce listed below:

Platform: Ubuntu 9.10 (Karmic)

```
bugreport$ ruby --version
ruby 1.9.1p376 (2009-12-07 revision 26041) [x86_64-linux]
```

RMagick command sequence: 

```
bugreport$ irb 
irb(main):001:0> require 'RMagick'
=> true
irb(main):002:0> puts Magick::Long_version
This is RMagick 2.12.2 ($Date: 2009/09/15 22:09:44 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 6.6.0-0 2010-03-03 Q8 http://www.imagemagick.org
Built for ruby 1.9.1
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
=> nil
irb(main):003:0> fn = 'original.jpg'
=> "original.jpg"
irb(main):004:0> orig = Magick::Image.read(fn).first
=> original.jpg JPEG 600x387 600x387+0+0 DirectClass 8-bit 849kb
irb(main):005:0> orig.colorspace
=> CMYKColorspace=12
irb(main):006:0> orig.colorspace = Magick::RGBColorspace
=> RGBColorspace=1
irb(main):007:0> orig.write('original_rmagick_rgb.jpg')
=> original.jpg=>original_rmagick_rgb.jpg JPEG 600x387 600x387+0+0 DirectClass 8-bit 724kb
irb(main):008:0> 
```

Image Magick convert command sequence: 

```
bugreport$ convert --version
Version: ImageMagick 6.6.0-0 2010-03-03 Q8 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2010 ImageMagick Studio LLC
Features: OpenMP 

bugreport$ convert original.jpg -colorspace rgb original_convert_rgb.jpg
```

**Comment by baror** [comment] 2010-04-28 06:21
Thanks for the details! This looks like an issue that has been affecting several people lately. We'll look into it as soon as we have a free moment, hopefully this weekend.

**Comment by baror** [comment] 2010-05-03 03:53
It looks like the issue was caused by an ImageMagick function change in version 6.5.1 and forward. RMagick in source should be fixed to use the new function when available, and the change will be in the next release.

If you can, please try to compile from source and see if the fix works for you. If not, please reopen.

**Closed as completed by baror** 2010-05-03 03:53 UTC

**Comment by jxtps** [comment] 2010-06-09 03:30
I cloned rmagick from github and followed the instructions on http://github.com/rmagick/rmagick/blob/master/README.rc but still got the same result as before. 

How can I confirm that I'm indeed running the rmagick built from source? Long_version reports (I had separately upgraded to the latest gem using sudo gem install rmagick, so I was already on 2.13.1): 

This is RMagick 2.13.1 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 6.6.2-3 2010-06-08 Q8 http://www.imagemagick.org
Built for ruby 1.9.1
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org

**Comment by baror** [comment] 2010-06-10 15:43
If you're running RMagick from source, the version of RMagick should be 0.0.0 (since it's unreleased). You may need to remove the RMagick gem before doing an install from source.

**Comment by jxtps** [comment] 2010-06-10 20:09
Fix worked, thanks!

**Comment by thijsc** [comment] 2010-09-06 18:29
It would be nice to have an official release with this fix, any plans for that?

**Comment by mltsy** [comment] 2011-05-10 16:14
Yes - a release with this fix would be greatly appreciated! :)

**Comment by gucki** [comment] 2011-11-03 20:20
This bug seems to be present again :(

**Comment by beirigo** [comment] 2011-11-10 14:00
yes  i can confirm that the bug is present again =/

**Comment by lukesutton** [comment] 2012-05-11 01:48
This bug is still present in 2.13.1

Is there at least a known work around?

**Comment by schneikai** [comment] 2012-05-31 10:20
here too. using 2.13.1

**Comment by schneikai** [comment] 2012-05-31 11:09
got it working like this:

``` ruby
# source image must have a cmyk color profile. if not, you have to assign a standard profile.
# you get those icc profiles on the interwebs
unless image.color_profile
  image.add_profile("#{Rails.root}/lib/USWebCoatedSWOP.icc")
end

# then you assing a rgb profile. this converts the image to rgb.
image.add_profile("#{Rails.root}/lib/sRGB.icc") 

# you dont need the profiles anymore
image.strip!
```

**Comment by pedrocss** [comment] 2013-07-17 18:39
**schneikai**: solution not worked for me. Using RMagic 2.13.1 and sRGB v4 profile.
