### ISSUE TITLE
RMagick doesn't support HDRI ImageMagick

### ISSUE THREAD

**Issue by Benabik** [rmagick-temp/rmagick#18] opened 2010-10-13 22:06 UTC
I'm trying to get RMagick to work with Fink's imagemagick package, but I get the following error:

> RMagick does not work when ImageMagick is configured for High Dynamic Range Images.
> Don't use the --enable-hdri option when configuring ImageMagick.

Some web searching turns up a [patch for pld-linux](http://www.mail-archive.com/pld-cvs-commit%40lists.pld-linux.org/msg212202.html):

```
--- RMagick-2.13.0/ext/RMagick/rmimage.c~      2009-12-21 11:34:57.000000000 0100
+++ RMagick-2.13.0/ext/RMagick/rmimage.c       2010-03-03 13:58:39.770186927 0100
@@ -9815,7 +9815,7 @@
 #else
             IndexPacket *indexes = GetIndexes(image);
 #endif
-            old_color = image->colormap[*indexes];
+            old_color = image->colormap[(unsigned long)*indexes];
         }
         if (!image->matte)
         {
--- RMagick-2.13.0/ext/RMagick/extconf.rb~     2009-12-24 07:03:02.000000000 
0100
+++ RMagick-2.13.0/ext/RMagick/extconf.rb      2010-03-03 14:00:35.276124598 
0100
@@ -151,15 +151,6 @@

   $magick_version = `Magick-config --version`.chomp

-  # Ensure ImageMagick is not configured for HDRI
-  unless checking_for("HDRI disabled version of ImageMagick") do
-    not (`Magick-config --version`["HDRI"])
-  end
-    exit_failure "\nCan't install RMagick #{RMAGICK_VERS}."+
-           "\nRMagick does not work when ImageMagick is configured for High 
ynamic Range Images."+
-           "\nDon't use the --enable-hdri option when configuring 
mageMagick.\n"
-  end
-
   # Save flags
   $CFLAGS     = ENV["CFLAGS"].to_s   + " " + `Magick-config --cflags`.chomp
   $CPPFLAGS   = ENV["CPPFLAGS"].to_s + " " + `Magick-config --cppflags`.chomp
```

**Comment by saurabhnanda** [comment] 2012-06-03 11:03
I'm stuck with the same problem. How does one solve this?

**Comment by joneshf** [comment] 2013-08-28 23:15
Having the same issue here on arch linux.  Can anyone comment on @bricef's fix?

**Comment by bricef** [comment] 2013-08-28 23:28
@joneshf I have no idea what I'm doing :) My branch is nothing but the patch above applied. I haven't really had a look at it in any depth. Didn't even know that it would be cross referenced here.

**Comment by joneshf** [comment] 2013-08-29 03:32
Maybe not, but your branch worked to install over here, so it's worth a look.

**Comment by jk779** [comment] 2013-09-04 11:05
This affects me on recent Arch-Linux. Maintainers decided to enable hdri - have to build it from source now which is very pleasant. Here's the commit on the Arch-side:
https://projects.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/imagemagick&id=ba309a9904a66d9581e461cad7c648043246bb79

I don't think that they will change that. Can we achieve a solution on rmagick's side?

**Comment by mejymejy** [comment] 2013-09-05 06:18
I'm with @jk779.  How difficult is this change?  What problem does enabling HDRI pose with the current rmagick?

**Comment by josemotanet** [comment] 2013-09-06 10:11
I also use Arch Linux and would like to see this fixed. :+1:

**Comment by linduxed** [comment] 2013-09-06 11:33
Same situation here.

**Comment by ghost** [comment] 2013-09-06 19:46
Please, fix this for Arch Linux  :)  +watching thread.

**Comment by heaven** [comment] 2013-09-12 07:51
Same here. :+1:

**Comment by whites11** [comment] 2013-09-16 13:16
+1

**Comment by peteonrails** [comment] 2013-09-19 21:38
@bricef's Fix works for me on Arch and I have not been able to find any ill effects, using both regular and HDR images. Has anyone issued a pull request to get this patch in to master?

**Comment by linduxed** [comment] 2013-09-25 08:20
While I think @bricef should go ahead and create a PR against master, considering there's been no activity on this repo for the past eight months, it might be easier to just use his fork.

**Comment by peteonrails** [comment] 2013-09-25 13:00
I agree that using @bricef's fork is easier once you've spent the time to find the solution. But to save future developers the time it takes to research the install issue, someone's got the beat a drum to get the root cause fixed. 

Folks can help get this issue resolved by not only making a little noise, but by confirming that the patch in the Pull Request works, does not cause any production issues, and that you've tested it.  

Thanks in advance!

**Comment by jhollinger** [comment] 2013-09-25 18:02
Ran across this while installing Redmine on Arch. Switched to @peteonrails's branch and it installed fine. I don't know what Redmine _does_ with rmagick, but everything seems to work.

**Comment by joneshf** [comment] 2013-09-25 21:12
There's a package that fixes this hdri business https://aur.archlinux.org/packages/imagemagick-no-hdri/

**Comment by FND** [comment] 2013-10-03 13:14
> Ran across this while installing Redmine on Arch. Switched to @peteonrails's
> branch and it installed fine. I don't know what Redmine _does_ with rmagick,
> but everything seems to work.

Ditto for [Vimdeck](https://github.com/tybenz/vimdeck) instead of Redmine.

**Comment by johnhamelink** [comment] 2013-10-09 20:07
@joneshf that package is out of date unfortunately

Would really like to see this implemented in master branch!

**Comment by budu** [comment] 2013-11-04 17:00
+1

**Comment by mmaiza** [comment] 2013-11-04 18:00
This is now available on the master, I will not yet package it for rubygems until the tests are upgraded.

**Closed as completed by mmaiza** 2013-11-04 18:00 UTC

**Comment by joneshf** [comment] 2013-11-04 21:21
@mmaiza Thanks!

**Comment by heaven** [comment] 2013-11-04 21:26
@mmaiza Thank you!

**Comment by ghost** [comment] 2014-01-15 08:44
> I will not yet package it for rubygems until the tests are upgraded.

@mmaiza As I'm not familiar with this gem + gem's tests. What tests need to be upgraded (and how)? Thx.

Cheers,
dg

**Comment by ioquatix** [comment] 2014-01-21 09:07
@mmaiza When are you going to release the update?

**Comment by gutenye** [comment] 2014-01-22 07:47
> @mmaiza When are you going to release the update?

+1 I also use ArchLinux.

**Comment by ioquatix** [comment] 2014-02-16 04:05
@mmaiza Just wondering when you are going to release this updated gem?

**Comment by ioquatix** [comment] 2014-03-27 01:10
@mmaiza Bump.

**Comment by ddevault** [comment] 2014-04-30 17:00
Updated gem when?

**Comment by Aethelflaed** [comment] 2014-06-19 14:23
Bump, same problem here with Archlinux an HDRI, when will the gem be updated ?

**Comment by ioquatix** [comment] 2014-06-19 22:37
@bf4 Perhaps you can help to get this moving?

**Comment by zarokima** [comment] 2014-06-26 16:10
@mmaiza 

Would be really nice to have the updated gem released

**Comment by bf4** [comment] 2014-06-26 16:27
if the gem is updated, someone just fork, and release as 'yourname-rmagick'
until the gem owner can add someone else as owner, or you petition rubygems
with evidence that the gem is truly abandoned

**Comment by iangreenleaf** [comment] 2014-06-27 01:18
With bundler, it's possible to install the gem straight from GitHub:

```
gem 'rmagick', :git => 'https://github.com/rmagick/rmagick.git', :ref => '79e1708c7f6792a3a90cb8cb3ffaeb74c58e092e', :require => 'RMagick'
```

Still, it's much nicer to have an official gem version released, for a number of reasons.

**Comment by brain64bit** [comment] 2014-06-27 06:54
i'm using manjaro which is archlinux distribution, <a href='https://aur.archlinux.org/packages/imagemagick-no-hdri/'>imagemagick-no-hdri</a> solve this problem.

```
sudo yaourt imagemagick-no-hdri
```

**Comment by jk779** [comment] 2014-06-30 22:38
@brain64bit off topic: please be careful using yaourt with sudo as it compiles as root. just use it without sudo and it'll ask you for a password when installing.

**Comment by vltr** [comment] 2014-07-05 19:58
@iangreenleaf thanks for the tip, it's the best solution so far for this problem until someone updates the official gem :)

**Comment by gpakosz** [comment] 2014-07-24 13:33
will RMagick be ever updated to support HDRI?

**Comment by ioquatix** [comment] 2014-07-24 13:34
@gpakosz The original maintainer is AWOL...? I'm thinking of forking it and releasing an update. Anyone else think that is a good idea? Surely someone else must be involved in the "rmagick" organisation.

**Comment by bf4** [comment] 2014-07-24 14:08
# READ THIS

I just _forked this repo and imported its issues to https://github.com/gemhome/rmagick_  let me know if you want to get push there. I don't intend to maintain it myself, rather to enable its continuing maintenance, and help get a new release out.

**Comment by ioquatix** [comment] 2014-07-24 14:11
@bf4 I've emailed the original maintainer from ages ago, got a reply, not sure what the outcome will be yet. There was already a branch from @bricef which appears to work because he merged this PR. Will let you know tomorrow if there is any positive movement.

**Comment by ioquatix** [comment] 2014-07-24 14:12
@bf4 if we don't make any positive movement by the end of next week, lets work on the proposed fork you've created. Please give me commit access if that is okay.

**Comment by bf4** [comment] 2014-07-24 14:24
done

**Comment by linduxed** [comment] 2014-07-24 14:29
I'll post a blog post later today on the state of affairs with regards to the development of rmagick (I've had a few talks with the main developer).

**Comment by bf4** [comment] 2014-07-24 15:17
Anything you can share here for a tl;dr?

**Comment by linduxed** [comment] 2014-07-25 04:33
The TL;DR is that unless work happens on a fork, no work is going to happen.

[Full explanation here](http://linduxed.com/blog/2014/07/25/the-state-of-rmagick-development/).

**Comment by ioquatix** [comment] 2014-07-25 04:41
Nice. I've actually got in touch with the original maintainer before @mmaiza and asked him for his suggestions: @baror - he was responsive and hopefully something comes of this communication. I think that the easiest option would be to release one final gem for the 2.x branch and then perhaps focus on the 3.x release.

I've actually started using Ruby VIPS which is pretty good but pretty low level.

As a community I'm pretty sure we can pull our heads together and make a decent final release for 2.x and then start fixing issues (e.g. tests) for a 3.x release. We could remove a lot of legacy crap (support for ruby 1.5 etc)

**Comment by ioquatix** [comment] 2014-07-25 04:46
@linduxed Thanks for the detailed information about your communications.

It is clear to me that @mmaiza is doing the project a MASSIVE disservice by not updating the gem or working on the project or even communicating. If he isn't capable of writing the code himself he should at least engage the community as much as possible, pass on the responsibility to people who at least are passionate to get the ball rolling.

**Comment by bf4** [comment] 2014-07-25 14:37
@ioquatix I agree.  This is a general problem in the Ruby ecosystem, where a project used by many can very easily become abandoned.  What's particularly strange, here, is that the whole issue could be fixed if @mmaiza did two things:
1. Add someone else as an owner to the `rmagick` org who can add more collaborators
2. Add probably that same someone as an owner of the gem on rubygems.org `gem owner -a myrubygemsaccountemail@example.com`

I'm involved here, in part, because this is a part I'd like to help solve (or at least ameliorate).  See the discussion on the rubygems-org list about creating a rubygems adoption center.  https://groups.google.com/d/topic/rubygems-org/niS5ZO9DNgk/discussion

Though I'd prefer work continue here, especially since the gem is part of an org, which makes it super easy, I'm also a little excited to test-drive 'adopting' the gem at https://github.com/gemhome/rmagick

Adopting a gem is a huge pain.  I'd love for there to a be a one-click button for a github repo/gem owner to click and transfer ownership / add as owner someone who can help maintain the gem.

**Comment by bf4** [comment] 2014-07-25 14:41
@baror can you just add me or someone as repo owner (or transfer it to another org) and gem owner and we'll take it from here?

**Comment by baror** [comment] 2014-07-25 15:15
Hey, everyone -

You can find the latest documentation that I know about for how to do a release here: https://github.com/rmagick/rmagick/wiki/Release-Process , but as you can see, it's almost four years old, so it's almost certainly stale.

Unfortunately, you need to get a bunch of permissions that only @mmaiza has. From this thread, it seems like the last time you all heard from @mmaiza was in November of last year.

Here's my plan:
- I'll do my best to figure out how to give permissions to all the right systems (github, rubygems, etc.) to @bf4 . I can't guarantee anything, since I'm not an owner myself, but I'll see what I can do.
- @bf4 should go ahead and add whoever else he sees fit as owners and then do a release.
- If you don't hear back from @mmaiza after a while (maybe 3 weeks?), consider removing him as an owner.

Does that sound reasonable to everyone?

Thanks,
- Omer.

**Comment by ioquatix** [comment] 2014-07-25 23:40
@baror sounds like a good plan of action.

**Comment by bf4** [comment] 2014-07-27 22:42
So, I have gem push now.  Give me a hash to point to and I'll build a release candidate

**Comment by ioquatix** [comment] 2014-07-27 23:14
@bf4, I've been using the current master in production using `:git => 'url'` in bundler. I think if you do a minor point release with this version it would be great. After that, you can close this ticket, and I'd suggest we start working on a 3.x release updating tests to `rspec` and removing legacy code.

**Comment by bf4** [comment] 2014-07-27 23:24
Done. http://rubygems.org/gems/rmagick/versions/2.13.3.rc1  I _think_ most of the release process should be deprecated in favor of gem build. need to confirm.. please confirm this release works...

I still don't have commit here, so we need to work on a fork, till @mmaiza gives me or someone else access (gem release is essentially unrelated to any repository)

**Comment by bf4** [comment] 2014-07-31 15:26
Ok, I'm going to push a real 2.13.3.

I've been looking at what part of the 'release process' is still required.  Most of it looks like it can go and be replaced by gem build. The whole redcarpet conversion of README.rc to README.html doesn't seem to have been done for a while... and is buggy, thought it does appear to be at http://www.imagemagick.org/RMagick/doc/  which we (someone) needs to look into updating.

I'm moving work to gemhome/rmagick until we get control of this repo.  At least we can merge that back in here if we get this back.

Hey, @linduxed we're famous! http://rubyweekly.com/issues/206  links to your post http://linduxed.com/blog/2014/07/25/the-state-of-rmagick-development/?utm_source=rubyweekly&utm_medium=email

**Comment by mockdeep** [comment] 2014-07-31 17:45
I came across this in ruby weekly. Thanks guys, I had some vague ambitions to fork it myself and do some code cleanup. Nice to see it maintained again.

**Comment by bf4** [comment] 2014-07-31 19:34
@mockdeep I'd be very happy to accept a few PRs or issue write-ups there then add you as a collaborator.  ([If we don't do it, no one will](https://speakerdeck.com/bf4/the-open-source-junkyard)).

**Comment by mockdeep** [comment] 2014-07-31 21:36
Thanks, I'll add some cards to our team's open source board. I'm particularly interested in code quality and getting the tests passing.

It's sad to see so many projects falling away from being maintained. Some I've tried to contribute to only to get radio silence, others people ask if they can maintain and also don't get any response. Seems like there should be some sort of statute of limitations on rubygems for how long a gem can go without an update before it is released to be handled by another willing maintainer. Almost like renewing a domain...

**Comment by bf4** [comment] 2014-07-31 22:44
That's an interesting idea.  You post it to the rubygems-org list
thread on the adoption center

**Comment by bf4** [comment] 2014-08-01 02:38
Ok, release out https://twitter.com/hazula/status/495035407546220544 https://github.com/gemhome/rmagick/commit/0fe89ec2c3f117cf19d24057c403318aa1150718
