### ISSUE TITLE
unable to install on windows8

### ISSUE THREAD

**Issue by phron** [rmagick-temp/rmagick#74] opened 2013-04-09 15:01 UTC
As in the title...
ImageMagick well installed on my system, but I always have an error when trying to install gem

 I still can't install rmagick gem... I'm using Ruby 1.9.3, Rails 3.2.13 on Windows8 (all installed via RailsInstaller). I have ImageMagick and MinGW installed, but I always have an error when running gem install which fails when checking for "wand/MagickWand.h"

Here the trace

Rails Environment Configuration.

   ruby:
     bin:        C:/RailsInstaller/Ruby1.9.3/bin/ruby.exe
     version:    ruby 1.9.3p392 (2013-02-22) [i386-mingw32]

rails:
  bin:        C:/RailsInstaller/Ruby1.9.3/bin/rails.bat
  version:    Rails 3.2.13

```
C:\RailsInstaller\Ruby1.9.3\bin>gem install rmagick --platform=ruby -- "--with-opt-include=C:/ImageMagick/SourceCode" "--with-opt-lib=C:/ImageMagick"
```

  Temporarily enhancing PATH to include DevKit...
    Building native extensions.  This could take a while...
    ERROR:  Error installing rmagick:
        ERROR: Failed to build gem native extension.

```
    C:/RailsInstaller/Ruby1.9.3/bin/ruby.exe extconf.rb --with-opt-include=C:/ImageMagick/SourceCode --with-opt-lib=C:/ImageMagick
```

checking for Ruby version >= 1.8.5... yes
checking for stdint.h... yes
checking for sys/types.h... yes
checking for wand/MagickWand.h... no

Can't install RMagick 2.13.2. Can't find MagickWand.h.
**\* extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include=${opt-dir}/include
        --with-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby1.9.3/bin/ruby

Gem files will remain installed in C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9
.1/gems/rmagick-2.13.2 for inspection.
Results logged to C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/rmagick-2
.13.2/ext/RMagick/gem_make.out

Any help would be appreciated

**Comment by bodrovis** [comment] 2013-04-10 16:52
Can this be connected to https://github.com/rmagick/rmagick/issues/66 ? I am using rmagick 2.13.1 with older version of ImageMagick on Windows and everything is working fine. I was using instruction in the Wiki section to install it.

**Comment by phron** [comment] 2013-04-10 17:38
Probably, it's a problem with the gem itself, I installed mini_magick instead and it seems to work fine

**Comment by bodrovis** [comment] 2013-04-11 14:11
Yeah, this is probably related to the gem. You could just try using v2.13.1 too - it might work :).

**Comment by rmagick-temp** [comment] 2013-04-13 20:21
RMagick installs just fine. Please pay attention to the error messages. The fact that it cannot find Magickwand.h means that your PATH is not setup properly. I have not myself installed it on win 8 but regardless of whether it is 7 or 8 or probably 9 you need to have all the imagemagick (with required libraries) installed and accessible which means you have to setup PATH, CPATH and LIBRARY_PATH to Imagemagick_installation_root, Imagemagick_installation\include and Imagemagick_installation\lib respectively. This is the gist of the installation minus some details of what dev libraries you want included.
@Bodrovis rmagick 2.13.1 will not work with 1.9.3 besides the issue is that he does not have his environment properly setup.
Finally there is a fundamental difference between mini-magick and rmagick. RMagick links in he Imagemagick imagemagick libraries and makes api call. Mini-magick just wraps around the imagemagick executables and starts a process every time you want to use an imagemagick feature. Because RMagick integrates the imagemagick there is a small memory penalty at the onset but then the performance and flexibility is superior. Mini-magick on the other hand starts with a smaller memory but then then memory and other system usages are worst as it kicks an system process with all the imagemagick memory and resources needs for every call.
Closing this.

**Closed as completed by rmagick-temp** 2013-04-13 20:21 UTC

**Comment by phron** [comment] 2013-04-14 08:29
Thanks for all... 
That was a problem in the paths (case sensitive !)... Now all seems to work perfectly ^_^ 
Thanks a lot too for the explanations about the differences between the 2 gems, it's important (for me at least) to understand the impacts of choosing one or other gem and this info is often not easy to find... Thanks again, you made my day better !

**Comment by twnklmehta** [comment] 2014-03-12 15:35
can you tell me how to install imagemagick on windows 8
